### ISSUE TITLE
Unhandled exception when running app created by create-react-native-tizen

### ISSUE THREAD

**Issue by dice14u** [Samsung/react-native-tizen-dotnet#11]
I installed the create-react-native-tizen dev tool from this system, bundled it (without modification)
and ran it to get the following error

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ReactNative.ReactRootView.StartReactApplication(IReactInstanceManager reactInstanceManager, String moduleName)
   at ReactNative.ReactProgram.OnCreate()
   at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at TestApp.TestApp.Main(String[] args)
```
https://github.com/Samsung/react-native-tizen-dotnet/blob/3eb1c3f152df56ea82495a10b38d7066fec7da4a/Devtools/react-native-tizen-scripts/template/Tizen/Program.cs#L72

**Comment by maomao9003** [comment]
Hi,

You use samsung tv? or tv emulator?

**Comment by dice14u** [comment]
the official emulator, though I have not tried again since june of last year.

**Comment by maomao9003** [comment]
@dice14u  Current, react-native-tizen-dotnet is not support emulator well.

After we support emulator, we will mention you!

Thanks for your feedback!
