### ISSUE TITLE
Unable to launch to TV

### ISSUE THREAD

**Issue by ctscoville** [Samsung/react-native-tizen-dotnet#24]
Whenever I run through the Readme and get to the `yarn launch` command at the end, I get the following error:

```
Run on TVdisconnectCommandRun on TV ============================== Run on TV start!
Run on TV================Prepare install
Run on TVworkspacePath=/Users/username/Developer/reactNativeTizen/Tizen/bin/Release/netcoreapp2.0/
Not window platfrom need chmod+x sdb shell
Run on TVPrepare to connect your target
Run on TVIt is first time to run the extension, restart the sdb
Run on TVBegin SDB restart
Run on TVkillServerCommand: "/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" kill-server
Run on TVKill completed: info: server not running

Run on TVstartServerCommand: "/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" start-server
Run on TVdisconnectCommand:"/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" disconnect 192.168.10.10
Run on TVStarted SDB server: * server not running. starting it now on port 26099 *
* server started successfully *

disconnectCommand is failed
Run on TVexec error: Error: Command failed: "/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" disconnect 192.168.10.10
error: server not running

Run on TVdisconnectCommand is failed
/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/launchTarget.js:150
                    throw error;
                    ^

Error: Command failed: "/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" disconnect 192.168.10.10
error: server not running

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
✨  Done in 5.35s.
```

Any ideas what might be causing this and how I can fix it?

**Comment by maomao9003** [comment]
Hi, 

The error shows your target can't start sdb server, I think you need **enable developer mode** first, you can anable it ref: https://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-device


Thanks for your feedback

**Comment by scottmont** [comment]
@ctscoville I had the exact same error.  I had to ensure I put in the PC ip address correctly when enabling development mode.

**Comment by ctscoville** [comment]
Thanks for your help.  I was able to get a sample web app running on the TV using Tizen Studio, so I verified that I can launch apps on the TV.  Now when I try to run `yarn launch` for the React Native sample app, it's getting a little farther along than I was previously, but it's failing in a different spot now:

```
...
Run on TVTrying to push the wgt to target device
Run on TVpushCommand:"/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" -s 192.168.10.10 push /Users/username/Developer/reactNativeTizen/Tizen/bin/Release/netcoreapp2.0/reactNativeTizen-1.0.0.tpk /opt/usr/home/
Failed to push to widget to target
Run on TVexec error: Error: Command failed: "/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" -s 192.168.10.10 push /Users/username/Developer/reactNativeTizen/Tizen/bin/Release/netcoreapp2.0/reactNativeTizen-1.0.0.tpk /opt/usr/home/
* The version of SDB client (2.3.0) is not same with that of SDB server (4.1.8).
  It may cause version compatibility problems.
  It is recommended to use SDB server with version 2.3.0. *
* The version of SDB client (2.3.0) is not same with that of SDB server (4.1.8).
  It may cause version compatibility problems.
  It is recommended to use SDB server with version 2.3.0. *
```

Do you think those SDB server/client version warnings are the problem?  I'm testing on a TV that has `tv-4.0` platform, but do I need to be using a TV with `tv-5.0`?

**Comment by TalhaArshad** [comment]
> Thanks for your help. I was able to get a sample web app running on the TV using Tizen Studio, so I verified that I can launch apps on the TV. Now when I try to run `yarn launch` for the React Native sample app, it's getting a little farther along than I was previously, but it's failing in a different spot now:
> 
> ```
> ...
> Run on TVTrying to push the wgt to target device
> Run on TVpushCommand:"/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" -s 192.168.10.10 push /Users/username/Developer/reactNativeTizen/Tizen/bin/Release/netcoreapp2.0/reactNativeTizen-1.0.0.tpk /opt/usr/home/
> Failed to push to widget to target
> Run on TVexec error: Error: Command failed: "/Users/username/Developer/reactNativeTizen/node_modules/tizen-tv-dev-cli/tools/sdb/mac/sdb" -s 192.168.10.10 push /Users/username/Developer/reactNativeTizen/Tizen/bin/Release/netcoreapp2.0/reactNativeTizen-1.0.0.tpk /opt/usr/home/
> * The version of SDB client (2.3.0) is not same with that of SDB server (4.1.8).
>   It may cause version compatibility problems.
>   It is recommended to use SDB server with version 2.3.0. *
> * The version of SDB client (2.3.0) is not same with that of SDB server (4.1.8).
>   It may cause version compatibility problems.
>   It is recommended to use SDB server with version 2.3.0. *
> ```
> 
> Do you think those SDB server/client version warnings are the problem? I'm testing on a TV that has `tv-4.0` platform, but do I need to be using a TV with `tv-5.0`?

I am having the exact same problem. Did you find any solution?
