### ISSUE TITLE
Yarn bundle script creates a redundant 'assets' folder

### ISSUE THREAD

**Issue by pbsamsung** [Samsung/react-native-tizen-dotnet#30]
If the React Native Tizen project contains picture assets (jpg, png files) the 'yarn bundle' command creates a redundant assets sub folder in the JuvoReactNative\Tizen\shared\res\assets. The result of this issues is having a copy of all the assets inside JuvoReactNative\Tizen\shared\res\assets\assets sub folder. The workaround for this issue is removal (deletion) of the copied folder. Otherwise application package size may be even doubled (at least grows significantly). 

Please, correct the script for bundling. In case the reproduction scenario is needed try to follow setup steps of the JuvoReactNative project described here: https://github.com/SamsungDForum/JuvoPlayer

**Comment by mseo12** [comment]
Hi,
I was following the guide README.md file but got error.

As you posted checked if there is redundant assets folder inside of that, but no.
But got error below, is there any dependency in yarn or node-js version?

C:\Project\JuvoPlayer\JuvoReactNative>yarn bundle --dev
yarn run v1.22.4
$ react-native-tizen bundle --dev
[Mon Apr 20 2020 16:27:10 GMT-0600 (GMT-06:00)][Util][INFO]: App current path : C:\Project\JuvoPlayer\JuvoReactNative\
[Mon Apr 20 2020 16:27:10 GMT-0600 (GMT-06:00)][Util][INFO]: App Name : JuvoReactNative
[Mon Apr 20 2020 16:27:10 GMT-0600 (GMT-06:00)][Util][INFO]: Loading config file from : C:\Project\JuvoPlayer\JuvoReactNative\package.json
[Mon Apr 20 2020 16:27:10 GMT-0600 (GMT-06:00)][Bundle][INFO]: Output Bundle Path: C:\Project\JuvoPlayer\JuvoReactNative\Tizen\shared\res
[Mon Apr 20 2020 16:27:10 GMT-0600 (GMT-06:00)][Bundle][INFO]: React Native will Bundle file with Platfrom: tizen
Scanning 602 folders for symlinks in C:\Project\JuvoPlayer\JuvoReactNative\node_modules (84ms)

Invalid regular expression: /(node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|Libraries\\Relay\\relay\\tools\\relayUnstableBatchedUpdates\.js|heapCapture\\bundle\.js)$/: Unterminated character class

child_process.js:669
    throw err;
    ^

Error: Command failed: node C:\Project\JuvoPlayer\JuvoReactNative\node_modules\react-native\local-cli\cli.js bundle --entry-file index.tizen.js --bundle-output C:\Project\JuvoPlayer\JuvoReactNative\Tizen\shared\res\index.tizen.bundle --platform tizen --assets-dest C:\Project\JuvoPlayer\JuvoReactNative\Tizen\shared\res\assets\ --dev false
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at C:\Project\JuvoPlayer\JuvoReactNative\node_modules\react-native-tizen-dotnet\build\bundle.js:56:33
    at Object.<anonymous> (C:\Project\JuvoPlayer\JuvoReactNative\node_modules\react-native-tizen-dotnet\build\bundle.js:57:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 27388,
  stdout: null,
  stderr: null
}
Done in 5.41s.

I think this bundle failure is causing the build below.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1566	Error reading resource 'JuvoReactNative.shared.res.index.tizen.bundle' -- 'Could not find file 'C:\Project\JuvoPlayer\JuvoReactNative\Tizen\shared\res\index.tizen.bundle'.'	JuvoReactNative	C:\Project\JuvoPlayer\JuvoReactNative\Tizen\CSC	1	Active

Thank you,
mseo
